### ISSUE TITLE
 java.net.UnknownHostException: raw.githubusercontent.com

### ISSUE THREAD

**Issue by RainUtopia** [zengcanxiang/Android-pack-plugin#1]
Execution failed for task ':app:downTask'.
> java.net.UnknownHostException: raw.githubusercontent.com

执行firmTask出现上面提示咋解决。。

**Comment by zengcanxiang** [comment]
这个是下载github上的waller渠道jar包。如果不能下载，考虑一下翻墙或者。通过浏览器下载好了。放到目录下。会检测本地是否存在------------------ 原始邮件 ------------------
发件人: "RainUtopia"<notifications@github.com>
发送时间: 2020年5月6日(星期三) 上午9:21
收件人: "zengcanxiang/Android-pack-plugin"<Android-pack-plugin@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [zengcanxiang/Android-pack-plugin]  java.net.UnknownHostException:raw.githubusercontent.com (#1)




 
Execution failed for task ':app:downTask'.
  
java.net.UnknownHostException: raw.githubusercontent.com
  
执行firmTask出现上面提示咋解决。。
 
&mdash;

**Comment by RainUtopia** [comment]
waller渠道jar包是啥，能给个链接么，thx

**Comment by zengcanxiang** [comment]
你直接下载这个吧。那个第三方的地址好像不行了。到时候，我得改下


[walle_cli.zip](https://github.com/zengcanxiang/Android-pack-plugin/files/4584704/walle_cli.zip)
